import { useMemo } from "react";
import { Helmet } from "react-helmet-async";
import { Link, useParams, Navigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Footer } from "@/components/Footer";
import { SiteHeader } from "@/components/SiteHeader";
import { BreadcrumbSchema, FAQSchema, HowToSchema, ArticleSchema } from "@/components/SEOSchema";
import { Sparkles, Palette, Heart, Cake, CheckCircle2, AlertTriangle, BookOpen, Calendar, Star } from "lucide-react";
import featuredCake1 from "@/assets/featured-cake-1.jpg";
import featuredCake2 from "@/assets/featured-cake-2.jpg";
import featuredCake3 from "@/assets/featured-cake-3.jpg";
import featuredCake4 from "@/assets/featured-cake-4.jpg";
import featuredCake5 from "@/assets/featured-cake-5.jpg";
import { CAKE_THEMES } from "@/data/cakeThemes";
import { THEME_DEEP } from "@/data/themeDeep";

const samples = [featuredCake1, featuredCake2, featuredCake3, featuredCake4, featuredCake5];

const LAST_UPDATED = "2026-06-25";

const ThemedCakePage = () => {
  const { theme: slug } = useParams<{ theme: string }>();

  const entry = useMemo(
    () => CAKE_THEMES.find((t) => t.slug === slug?.toLowerCase()),
    [slug],
  );

  if (!entry) return <Navigate to="/free-ai-cake-designer" replace />;

  const { title, description, audience } = entry;
  const deep = THEME_DEEP[entry.slug];
  const url = `https://cakeaiartist.com/birthday-cake-theme/${entry.slug}`;
  const pageTitle = `${title} Birthday Cake — Designs, Tips & Free AI Maker`;
  const metaDesc = `Design a ${title.toLowerCase()} birthday cake in 30 seconds. ${deep?.story.slice(0, 100) ?? description.slice(0, 110)} Free AI cake maker with expert tips.`;

  const faqs = [
    {
      question: `What makes a great ${title} birthday cake?`,
      answer: deep
        ? `The strongest ${title} cakes share five details: ${deep.checklist.slice(0, 3).join("; ")}. Skipping any of these is what makes generic bakery ${title.toLowerCase()} cakes look amateurish.`
        : `A great ${title} cake commits fully to the theme — colour palette, motifs and lettering all need to match.`,
    },
    {
      question: `What colours work for a ${title} cake?`,
      answer: deep
        ? `The canonical ${title} palette is ${deep.colours.join(", ")}. Our AI uses these exact tones by default, so the cake reads as ${title.toLowerCase()} at a glance, not as a generic birthday cake.`
        : `The ${title} palette is well-established and our AI uses it by default.`,
    },
    {
      question: `Is the ${title} cake design suitable for ${audience === "anyone" ? "all ages" : audience}?`,
      answer: `${title} cakes work best for ${audience}, but the AI adapts the design intensity to the age you enter — a 4-year-old gets a playful version, an adult gets a sophisticated one with the same theme cues.`,
    },
    {
      question: `How is the ${title} cake design generated by AI?`,
      answer: `Our model is trained on thousands of professional ${title.toLowerCase()} cake photos by working bakers, and post-renders the name in clear lettering. Type the recipient's name and the AI generates a ${title.toLowerCase()}-themed cake in 30 seconds — front, side, and top-down views, all consistent.`,
    },
    {
      question: `Is the ${title} cake design free?`,
      answer: `Yes. Generate 5 ${title.toLowerCase()} cake designs for free, no credit card. Premium unlocks unlimited generations, HD downloads and the AI party planner.`,
    },
    {
      question: `Can I customise the ${title} cake colours, age and message?`,
      answer: `Yes. After picking the ${title.toLowerCase()} theme, add any name, age, custom message and even a reference photo. The AI keeps the ${title.toLowerCase()} aesthetic intact while honouring your specifics.`,
    },
    {
      question: `Can I take this AI ${title} cake design to a local bakery?`,
      answer: `Yes — that's one of the most common uses. The three-view render (front, side, top-down) gives any bakery enough information to recreate the cake in fondant or buttercream.`,
    },
    {
      question: `Why are AI-generated ${title} cakes better than ChatGPT or Gemini ones?`,
      answer: `General-purpose AIs (ChatGPT, Gemini, DALL-E) often distort the name, get ${title.toLowerCase()} colours wrong, or add weird artefacts to the cake structure. Our model is purpose-built for cakes — accurate proportions, correct ${title.toLowerCase()} motifs, and guaranteed correct name spelling.`,
    },
  ];

  const howToSteps = [
    { name: `Open the ${title} cake designer`, text: `Click below to open the free designer with the ${title.toLowerCase()} theme pre-selected.` },
    { name: "Enter the recipient's name and age", text: `Type the name (any spelling) and age — the AI will personalise the ${title.toLowerCase()} cake around them.` },
    { name: "Add an optional custom message", text: `Pick from the message ideas below, or write your own short greeting.` },
    { name: "Generate three cake views", text: `The AI generates a front view, side view and top-down view of the ${title.toLowerCase()} cake in ~30 seconds.` },
    { name: "Share or download", text: `Share the animated cake link with birthday music, or download the JPG.` },
  ];

  return (
    <div className="min-h-screen bg-gradient-surface">
      <Helmet>
        <title>{pageTitle}</title>
        <meta name="description" content={metaDesc} />
        <link rel="canonical" href={url} />
        <meta property="og:title" content={pageTitle} />
        <meta property="og:description" content={metaDesc} />
        <meta property="og:url" content={url} />
        <meta property="og:type" content="article" />
        <meta property="og:image" content="https://cakeaiartist.com/hero-cake.jpg" />
        <meta name="author" content="Cake AI Artist Editorial Team" />
      </Helmet>

      <BreadcrumbSchema items={[
        { name: "Home", url: "https://cakeaiartist.com" },
        { name: "Cake Themes", url: "https://cakeaiartist.com/free-ai-cake-designer" },
        { name: title, url },
      ]} />
      <FAQSchema faqs={faqs} />
      <HowToSchema
        name={`How to design a ${title} birthday cake`}
        description={`Step-by-step guide to designing a personalised ${title.toLowerCase()} birthday cake in 30 seconds.`}
        totalTime="PT30S"
        steps={howToSteps}
      />
      <ArticleSchema
        headline={pageTitle}
        description={metaDesc}
        datePublished="2026-06-15"
        dateModified={LAST_UPDATED}
        author="Cake AI Artist Editorial Team"
        url={url}
      />

      <SiteHeader />

      <main className="max-w-5xl mx-auto px-4 py-10">
        {/* EEAT byline */}
        <div className="text-xs text-muted-foreground mb-4 flex flex-wrap items-center gap-3">
          <span className="flex items-center gap-1"><BookOpen className="w-3.5 h-3.5" /> Cake AI Artist Editorial Team</span>
          <span className="flex items-center gap-1"><Calendar className="w-3.5 h-3.5" /> Last updated: {new Date(LAST_UPDATED).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</span>
          <span className="flex items-center gap-1"><Star className="w-3.5 h-3.5" /> 4.9/5 from 2,800+ users</span>
        </div>

        {/* Hero */}
        <section className="text-center mb-12">
          <p className="text-sm uppercase tracking-wider text-party-pink font-semibold mb-3">
            {title} cake design
          </p>
          <h1 className="text-4xl md:text-6xl font-bold mb-4 text-foreground">
            {title} Birthday Cake
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-6">
            {description}
          </p>
          <Link to={`/free-ai-cake-designer?theme=${encodeURIComponent(entry.slug)}`}>
            <Button size="lg" className="bg-gradient-party text-white font-bold text-lg px-8 py-6 shadow-elegant hover:scale-105 transition-transform">
              <Sparkles className="w-5 h-5 mr-2" />
              Design {title} Cake Free →
            </Button>
          </Link>
          <p className="text-xs text-muted-foreground mt-3">
            ✅ Free • ✅ 30 seconds • ✅ Any name, spelled correctly
          </p>
        </section>

        {/* Story / why-it-matters */}
        {deep && (
          <section className="mb-12">
            <Card className="p-6 md:p-8 bg-card border-2 border-party-pink/20">
              <h2 className="text-2xl md:text-3xl font-bold mb-4">The story behind {title} cakes</h2>
              <p className="text-base text-muted-foreground mb-4 leading-relaxed">{deep.story}</p>
              <div className="grid sm:grid-cols-2 gap-4 text-sm">
                <div>
                  <p className="font-semibold text-foreground mb-1">Best for</p>
                  <p className="text-muted-foreground">{deep.bestFor.join(" · ")}</p>
                </div>
                <div>
                  <p className="font-semibold text-foreground mb-1">Canonical palette</p>
                  <p className="text-muted-foreground">{deep.colours.join(" · ")}</p>
                </div>
              </div>
            </Card>
          </section>
        )}

        {/* Sample gallery */}
        <section className="mb-12">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-6">
            {title} cake design ideas
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
            {samples.map((src, i) => (
              <Card key={i} className="overflow-hidden hover:shadow-elegant transition-shadow">
                <img
                  src={src}
                  alt={`${title} birthday cake design idea — style ${i + 1}`}
                  loading="lazy"
                  className="w-full aspect-square object-cover"
                />
              </Card>
            ))}
          </div>
        </section>

        {/* Expert checklist */}
        {deep && (
          <section className="mb-12">
            <Card className="p-6 md:p-8">
              <h2 className="text-2xl md:text-3xl font-bold mb-2 flex items-center gap-2">
                <CheckCircle2 className="w-7 h-7 text-party-pink" />
                What makes a great {title} cake
              </h2>
              <p className="text-sm text-muted-foreground mb-5">
                Five details working bakers agree on — and that our AI replicates by default.
              </p>
              <ol className="space-y-3 text-sm">
                {deep.checklist.map((item, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="font-bold text-party-pink shrink-0">{i + 1}.</span>
                    <span className="text-muted-foreground">{item}</span>
                  </li>
                ))}
              </ol>
            </Card>
          </section>
        )}

        {/* Common mistakes */}
        {deep && (
          <section className="mb-12">
            <Card className="p-6 md:p-8 bg-amber-50/50 dark:bg-amber-900/10 border-amber-200">
              <h2 className="text-2xl md:text-3xl font-bold mb-2 flex items-center gap-2 text-foreground">
                <AlertTriangle className="w-7 h-7 text-amber-600" />
                3 mistakes to avoid with {title} cakes
              </h2>
              <p className="text-sm text-muted-foreground mb-5">
                These are the most common errors we see in real bakery and DIY {title.toLowerCase()} cakes.
              </p>
              <ul className="space-y-3 text-sm">
                {deep.mistakes.map((item, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="text-amber-600 shrink-0">✗</span>
                    <span className="text-muted-foreground">{item}</span>
                  </li>
                ))}
              </ul>
            </Card>
          </section>
        )}

        {/* Message ideas */}
        {deep && (
          <section className="mb-12">
            <Card className="p-6 md:p-8">
              <h2 className="text-2xl md:text-3xl font-bold mb-2">{title} cake message ideas</h2>
              <p className="text-sm text-muted-foreground mb-5">
                Short messages that pair beautifully with the {title.toLowerCase()} aesthetic. Replace [age] with the real age.
              </p>
              <ul className="grid sm:grid-cols-2 gap-2 text-sm">
                {deep.messageIdeas.map((m, i) => (
                  <li key={i} className="text-muted-foreground p-3 rounded-md bg-muted/50">
                    "{m.replace(/\{NAME\}/g, "[Name]")}"
                  </li>
                ))}
              </ul>
            </Card>
          </section>
        )}

        {/* Features */}
        <section className="grid md:grid-cols-3 gap-6 mb-12">
          <Card className="p-6">
            <Palette className="w-8 h-8 text-party-pink mb-3" />
            <h3 className="font-bold text-lg mb-2">True {title} aesthetic</h3>
            <p className="text-sm text-muted-foreground">
              No generic clipart. The AI captures the actual {title.toLowerCase()} aesthetic — colours, props, mood and lettering.
            </p>
          </Card>
          <Card className="p-6">
            <Cake className="w-8 h-8 text-party-pink mb-3" />
            <h3 className="font-bold text-lg mb-2">3 cake views</h3>
            <p className="text-sm text-muted-foreground">
              Front, side and top-down renders — you see the {title.toLowerCase()} cake the way a bakery photo would show it.
            </p>
          </Card>
          <Card className="p-6">
            <Heart className="w-8 h-8 text-party-pink mb-3" />
            <h3 className="font-bold text-lg mb-2">Share with music</h3>
            <p className="text-sm text-muted-foreground">
              Send a link with a spinning 3D {title.toLowerCase()} cake reveal and birthday jingle — perfect for WhatsApp and Instagram.
            </p>
          </Card>
        </section>

        {/* How to */}
        <section className="mb-12">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-6">
            How to design your {title} cake
          </h2>
          <ol className="max-w-2xl mx-auto space-y-3 text-base">
            {howToSteps.map((step, i) => (
              <li key={i}>
                <strong>{i + 1}.</strong> {step.text}
              </li>
            ))}
          </ol>
          <div className="text-center mt-6">
            <Link to={`/free-ai-cake-designer?theme=${encodeURIComponent(entry.slug)}`}>
              <Button size="lg" className="bg-gradient-party text-white font-bold">
                Start {title} Cake →
              </Button>
            </Link>
          </div>
        </section>

        {/* FAQ */}
        <section className="mb-12 max-w-3xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold mb-6 text-center">Frequently asked questions</h2>
          <div className="space-y-4">
            {faqs.map((f, i) => (
              <Card key={i} className="p-5">
                <h3 className="font-semibold mb-2 text-foreground">{f.question}</h3>
                <p className="text-sm text-muted-foreground">{f.answer}</p>
              </Card>
            ))}
          </div>
        </section>

        {/* Internal links */}
        <section className="mb-12 text-center">
          <h2 className="text-xl font-bold mb-4">More cake themes to explore</h2>
          <div className="flex flex-wrap gap-2 justify-center max-w-3xl mx-auto">
            {CAKE_THEMES.filter((t) => t.slug !== entry.slug)
              .slice(0, 20)
              .map((t) => (
                <Link
                  key={t.slug}
                  to={`/birthday-cake-theme/${t.slug}`}
                  className="text-sm px-3 py-1.5 rounded-full border border-border hover:bg-party-pink/10 hover:border-party-pink transition-colors"
                >
                  {t.title}
                </Link>
              ))}
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default ThemedCakePage;
