import { useState } from "react";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { HeroCakeWithFlames } from "@/components/HeroCakeWithFlames";
import featuredCake1 from "@/assets/featured-cake-1.jpg";
import featuredCake2 from "@/assets/featured-cake-2.jpg";
import featuredCake3 from "@/assets/featured-cake-3.jpg";
import featuredCake4 from "@/assets/featured-cake-4.jpg";
import featuredCake5 from "@/assets/featured-cake-5.jpg";
import { Sparkles } from "lucide-react";

interface CakeWallProps {
  cakeCount?: number;
}

interface Tile {
  src?: string;
  alt: string;
  rotate: string;
  delay: string;
  span?: string;
  hero?: boolean;
}

export const CakeWall = ({ cakeCount = 5000 }: CakeWallProps) => {
  const [lightbox, setLightbox] = useState<string | null>(null);

  const tiles: Tile[] = [
    {
      hero: true,
      alt: "Personalized birthday cake designed by AI — Cake AI Artist",
      rotate: "-rotate-2",
      delay: "0s",
      span: "row-span-2",
    },
    {
      src: featuredCake1,
      alt: "AI-designed pink unicorn birthday cake for kids",
      rotate: "rotate-2",
      delay: "0.4s",
    },
    {
      src: featuredCake2,
      alt: "Personalized anniversary cake design by AI",
      rotate: "-rotate-1",
      delay: "0.8s",
    },
    {
      src: featuredCake3,
      alt: "Custom wedding cake design generated by AI in 30 seconds",
      rotate: "rotate-1",
      delay: "1.2s",
      span: "row-span-2",
    },
    {
      src: featuredCake4,
      alt: "AI birthday cake design with name and candles",
      rotate: "-rotate-2",
      delay: "1.6s",
    },
    {
      src: featuredCake5,
      alt: "Personalized celebration cake — best AI cake designer",
      rotate: "rotate-2",
      delay: "2s",
    },
  ];

  return (
    <div className="relative">
      {/* Vivid party gradient blob behind the wall */}
      <div className="pointer-events-none absolute -inset-8 bg-gradient-to-tr from-party-pink/40 via-party-purple/30 to-party-gold/40 blur-3xl rounded-full" />

      {/* The wall */}
      <div className="relative grid grid-cols-2 auto-rows-[110px] sm:auto-rows-[140px] md:auto-rows-[160px] gap-3 md:gap-4">
        {tiles.map((t, i) => (
          <button
            key={i}
            type="button"
            onClick={() => t.src && setLightbox(t.src)}
            style={{ animationDelay: t.delay }}
            className={`group relative ${t.span ?? ""} ${t.rotate} animate-wall-bob bg-white rounded-2xl p-1.5 shadow-party hover:shadow-2xl hover:scale-105 hover:rotate-0 transition-all duration-300 overflow-hidden`}
            aria-label={t.alt}
          >
            <div className="w-full h-full rounded-xl overflow-hidden bg-gradient-to-br from-party-pink/10 to-party-purple/10">
              {t.hero ? (
                <div className="w-full h-full flex items-center justify-center">
                  <HeroCakeWithFlames />
                </div>
              ) : (
                <img
                  src={t.src}
                  alt={t.alt}
                  loading="lazy"
                  width={400}
                  height={400}
                  className="w-full h-full object-cover"
                />
              )}
            </div>

            {/* Chip on hero tile */}
            {t.hero && (
              <span className="absolute top-2 left-2 z-10 inline-flex items-center gap-1 bg-gradient-party text-white text-[10px] md:text-xs font-bold px-2 py-1 rounded-full shadow-lg">
                <Sparkles className="w-3 h-3" />
                AI-designed
              </span>
            )}

            {/* Social proof chip on a smaller tile */}
            {i === 4 && (
              <span className="absolute -bottom-1 left-1/2 -translate-x-1/2 z-10 whitespace-nowrap bg-white text-foreground text-[10px] md:text-xs font-bold px-2.5 py-1 rounded-full shadow-lg border-2 border-party-gold">
                🎂 1 of {cakeCount.toLocaleString()}+
              </span>
            )}
          </button>
        ))}
      </div>

      {/* Lightbox */}
      <Dialog open={!!lightbox} onOpenChange={(o) => !o && setLightbox(null)}>
        <DialogContent className="max-w-3xl bg-transparent border-0 p-0 shadow-none">
          {lightbox && (
            <img
              src={lightbox}
              alt="AI-designed personalized cake — full preview"
              className="w-full h-auto rounded-2xl"
            />
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};
