import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

interface PartyPack {
  invitation_url: string;
  thank_you_card_url: string;
  banner_url: string;
  cake_topper_url: string;
  place_cards_url: string;
}

export async function generatePartyPackPDF(
  partyPack: PartyPack,
  name: string,
  occasion: string
): Promise<Blob> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const PAGE_WIDTH = 612; // 8.5 inches in points
  const PAGE_HEIGHT = 792; // 11 inches in points

  const items = [
    { url: partyPack.invitation_url, title: "Invitation Card" },
    { url: partyPack.thank_you_card_url, title: "Thank You Card" },
    { url: partyPack.banner_url, title: "Party Banner" },
    { url: partyPack.cake_topper_url, title: "Cake Topper" },
    { url: partyPack.place_cards_url, title: "Place Cards" },
  ];

  // --- Title Page ---
  const titlePage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const titleText = `${name}'s ${occasion}`;
  const titleWidth = fontBold.widthOfTextAtSize(titleText, 24);
  titlePage.drawText(titleText, {
    x: (PAGE_WIDTH - titleWidth) / 2,
    y: PAGE_HEIGHT - 144,
    size: 24,
    font: fontBold,
    color: rgb(0, 0, 0),
  });

  const subtitle = "Complete Party Pack";
  const subtitleWidth = font.widthOfTextAtSize(subtitle, 18);
  titlePage.drawText(subtitle, {
    x: (PAGE_WIDTH - subtitleWidth) / 2,
    y: PAGE_HEIGHT - 216,
    size: 18,
    font,
    color: rgb(0, 0, 0),
  });

  const containsLabel = "This PDF contains:";
  const containsWidth = font.widthOfTextAtSize(containsLabel, 12);
  titlePage.drawText(containsLabel, {
    x: (PAGE_WIDTH - containsWidth) / 2,
    y: PAGE_HEIGHT - 324,
    size: 12,
    font,
    color: rgb(0, 0, 0),
  });

  let yPos = PAGE_HEIGHT - 374;
  for (const item of items) {
    const bulletText = `• ${item.title}`;
    const bulletWidth = font.widthOfTextAtSize(bulletText, 10);
    titlePage.drawText(bulletText, {
      x: (PAGE_WIDTH - bulletWidth) / 2,
      y: yPos,
      size: 10,
      font,
      color: rgb(0, 0, 0),
    });
    yPos -= 22;
  }

  const footer1 = "Print each page on high-quality paper for best results";
  const footer1Width = font.widthOfTextAtSize(footer1, 8);
  titlePage.drawText(footer1, {
    x: (PAGE_WIDTH - footer1Width) / 2,
    y: 108,
    size: 8,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  const footer2 = "Generated by Cake AI Artist";
  const footer2Width = font.widthOfTextAtSize(footer2, 8);
  titlePage.drawText(footer2, {
    x: (PAGE_WIDTH - footer2Width) / 2,
    y: 72,
    size: 8,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  // --- Image Pages ---
  for (let i = 0; i < items.length; i++) {
    const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

    // Title
    const itemTitleWidth = fontBold.widthOfTextAtSize(items[i].title, 14);
    page.drawText(items[i].title, {
      x: (PAGE_WIDTH - itemTitleWidth) / 2,
      y: PAGE_HEIGHT - 36,
      size: 14,
      font: fontBold,
      color: rgb(0, 0, 0),
    });

    try {
      const response = await fetch(items[i].url);
      const imageBytes = new Uint8Array(await response.arrayBuffer());

      // Detect format from bytes
      let image;
      if (imageBytes[0] === 0x89 && imageBytes[1] === 0x50) {
        image = await pdf.embedPng(imageBytes);
      } else {
        image = await pdf.embedJpg(imageBytes);
      }

      const maxWidth = PAGE_WIDTH - 72; // 0.5 inch margins
      const maxHeight = PAGE_HEIGHT - 108; // top title + bottom footer
      const scale = Math.min(maxWidth / image.width, maxHeight / image.height, 1);
      const drawWidth = image.width * scale;
      const drawHeight = image.height * scale;

      page.drawImage(image, {
        x: (PAGE_WIDTH - drawWidth) / 2,
        y: PAGE_HEIGHT - 54 - drawHeight,
        width: drawWidth,
        height: drawHeight,
      });
    } catch (error) {
      console.error(`Failed to load image for ${items[i].title}:`, error);
      const errText = `Failed to load ${items[i].title}`;
      const errWidth = font.widthOfTextAtSize(errText, 10);
      page.drawText(errText, {
        x: (PAGE_WIDTH - errWidth) / 2,
        y: PAGE_HEIGHT / 2,
        size: 10,
        font,
        color: rgb(0.6, 0, 0),
      });
    }

    // Footer
    const pageNum = `Page ${i + 2} of ${items.length + 1}`;
    const pageNumWidth = font.widthOfTextAtSize(pageNum, 8);
    page.drawText(pageNum, {
      x: (PAGE_WIDTH - pageNumWidth) / 2,
      y: 36,
      size: 8,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
  }

  const pdfBytes = await pdf.save();
  return new Blob([pdfBytes.buffer as ArrayBuffer], { type: "application/pdf" });
}
