import jsPDF from "jspdf";

interface PartyPack {
  invitation_url: string;
  thank_you_card_url: string;
  banner_url: string;
  cake_topper_url: string;
  place_cards_url: string;
}

export async function generatePartyPackPDF(
  partyPack: PartyPack,
  name: string,
  occasion: string
): Promise<Blob> {
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "in",
    format: "letter" // 8.5 x 11 inches
  });

  const items = [
    { url: partyPack.invitation_url, title: "Invitation Card" },
    { url: partyPack.thank_you_card_url, title: "Thank You Card" },
    { url: partyPack.banner_url, title: "Party Banner" },
    { url: partyPack.cake_topper_url, title: "Cake Topper" },
    { url: partyPack.place_cards_url, title: "Place Cards" }
  ];

  // Helper to load image as data URL
  const loadImage = async (url: string): Promise<string> => {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  };

  // Add title page
  pdf.setFontSize(24);
  pdf.text(`${name}'s ${occasion}`, 4.25, 2, { align: "center" });
  
  pdf.setFontSize(18);
  pdf.text("Complete Party Pack", 4.25, 3, { align: "center" });
  
  pdf.setFontSize(12);
  pdf.text("This PDF contains:", 4.25, 4.5, { align: "center" });
  
  pdf.setFontSize(10);
  let yPos = 5.2;
  items.forEach((item) => {
    pdf.text(`• ${item.title}`, 4.25, yPos, { align: "center" });
    yPos += 0.3;
  });

  pdf.setFontSize(8);
  pdf.text("Print each page on high-quality paper for best results", 4.25, 9.5, { align: "center" });
  pdf.text("Generated by Cake AI Artist", 4.25, 10, { align: "center" });

  // Add each item on a separate page
  for (let i = 0; i < items.length; i++) {
    pdf.addPage();
    
    // Add item title at top
    pdf.setFontSize(14);
    pdf.text(items[i].title, 4.25, 0.5, { align: "center" });

    try {
      const imageData = await loadImage(items[i].url);
      
      // Calculate dimensions to fit on page with margins
      const maxWidth = 7.5; // inches (8.5 - 0.5 margin on each side)
      const maxHeight = 9.5; // inches (11 - 1 top margin - 0.5 bottom margin)
      
      // Add image centered on page
      pdf.addImage(imageData, "PNG", 0.5, 1, maxWidth, maxHeight, undefined, "FAST");
    } catch (error) {
      console.error(`Failed to load image for ${items[i].title}:`, error);
      pdf.setFontSize(10);
      pdf.text(`Failed to load ${items[i].title}`, 4.25, 5.5, { align: "center" });
      pdf.text("Please download this item individually", 4.25, 6, { align: "center" });
    }

    // Add footer with page number
    pdf.setFontSize(8);
    pdf.text(`Page ${i + 2} of ${items.length + 1}`, 4.25, 10.5, { align: "center" });
  }

  return pdf.output("blob");
}